services:
  trino:
    image: trinodb/trino:405
    container_name: trino
    hostname: trino
    ports:
      - 8080:8080
    volumes:
      - ./conf/hive.properties:/etc/trino/catalog/hive.properties
      - ./conf/iceberg.properties:/etc/trino/catalog/iceberg.properties
    networks:
      - trino
    depends_on:
      - metastore
    extra_hosts:
      - "host.docker.internal:host-gateway"

  metastore-db:
    image: mariadb
    container_name: metastore-db
    ports:
      - 3306:3306
    networks:
      - trino
    volumes:
      - metastore-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  metastore:
    image: bitsondatadev/hive-metastore:latest
    platform: linux/amd64
    container_name: metastore
    ports:
      - 9083:9083
    networks:
      - trino
    volumes:
      - ./metastore/metastore-site.xml:/opt/hive-metastore/conf/metastore-site.xml
      - ./metastore/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    command: /opt/hive-metastore/bin/start-metastore -p 9083
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"

  minio:
        image: minio/minio:RELEASE.2024-07-16T23-46-41Z-cpuv1
        container_name: minio
        networks:
          - trino
        ports:
          - 9000:9000
          - 9001:9001
        command: server /data --console-address ":9001"
        volumes:
        - minio:/data
        environment:
          - MINIO_ROOT_USER=${MINIO_ROOT_USER}
          - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
        extra_hosts:
          - "host.docker.internal:host-gateway"

networks:
  trino:

volumes:
  metastore-db:
  minio:
